// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace PowerLinesAI
{
    public partial class ResultModel
    {
        public const string RetrainFilePath =  @"C:\Repos\power-lines-ai\PowerLinesAI\PowerLinesAI\Results.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader);
        }



        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }


        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"division", @"division"),new InputOutputColumnPair(@"halfTimeResult", @"halfTimeResult")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"fullTimeHomeGoals", @"fullTimeHomeGoals"),new InputOutputColumnPair(@"fullTimeAwayGoals", @"fullTimeAwayGoals"),new InputOutputColumnPair(@"halfTimeHomeGoals", @"halfTimeHomeGoals"),new InputOutputColumnPair(@"halfTimeAwayGoals", @"halfTimeAwayGoals"),new InputOutputColumnPair(@"homeOddsAverage", @"homeOddsAverage"),new InputOutputColumnPair(@"drawOddsAverage", @"drawOddsAverage"),new InputOutputColumnPair(@"awayOddsAverage", @"awayOddsAverage")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"homeTeam",outputColumnName:@"homeTeam"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"awayTeam",outputColumnName:@"awayTeam"))      
                                    .Append(mlContext.Transforms.Conversion.ConvertType(@"date", @"date"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"division",@"halfTimeResult",@"fullTimeHomeGoals",@"fullTimeAwayGoals",@"halfTimeHomeGoals",@"halfTimeAwayGoals",@"homeOddsAverage",@"drawOddsAverage",@"awayOddsAverage",@"homeTeam",@"awayTeam",@"date"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"fullTimeResult",inputColumnName:@"fullTimeResult",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=4038,MinimumExampleCountPerLeaf=20,LearningRate=0.999999776672986,LabelColumnName=@"fullTimeResult",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.830977049299901,FeatureFraction=0.993647095123888,L1Regularization=2.00448953094004E-10,L2Regularization=0.0684875065499915},MaximumBinCountPerFeature=274}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
